print('Bom dia!')
nome = input('Qual é o seu nome?')
idade = input('Qual é a sua idade?')
altura = input('Qual é a sua altura?')
print('Bem vindo,' ,nome , '! aqui estão suas informações:')
print(idade,altura)
